nodeLinker: node-modules

# GitHub private 저장소 접근을 위한 설정
# GITHUB_TOKEN 환경 변수를 설정해야 합니다
# 환경 변수 설정: export GITHUB_TOKEN=your_token_here

# Yarn 2+ 에서는 git 설정을 지원합니다
# GITHUB_TOKEN 환경 변수가 설정되어 있으면 자동으로 사용됩니다
# package.json의 GitHub URL은 토큰 없이 설정해도 됩니다

# 참고: Yarn이 자동으로 GITHUB_TOKEN 환경 변수를 사용하여 인증합니다
# 만약 작동하지 않으면 install-with-token.sh 스크립트를 사용하세요
